//
//  StyleKit.swift
//  GaugeArrow
//
//  Created by Matej Dunik on 12/27/18.
//  Copyright © 2018 PixelCut. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class StyleKit : NSObject {

    //// Drawing Methods

    @objc dynamic public class func drawGauge(progressColor: UIColor = UIColor(red: 0.517, green: 0.704, blue: 0.095, alpha: 1.000), remainColor: UIColor = UIColor(red: 0.719, green: 0.735, blue: 0.683, alpha: 1.000), progress: CGFloat = 1, startAngle: CGFloat = 90, lineWidth: CGFloat = 3, size: CGSize = CGSize(width: 100, height: 100)) {

        //// Variable Declarations
        let endAngle: CGFloat = 360 * (1 - progress) - startAngle
        let padding: CGFloat = lineWidth / 2.0
        let frame = CGRect(x: padding, y: padding, width: size.width - lineWidth, height: size.height - lineWidth)

        //// Remain Frame Drawing
        let remainFramePath = UIBezierPath(ovalIn: frame)
        remainColor.setStroke()
        remainFramePath.lineWidth = lineWidth
        remainFramePath.stroke()


        //// Progress Frame Drawing
        let progressFrameRect = frame
        let progressFramePath = UIBezierPath()
        progressFramePath.addArc(withCenter: CGPoint(x: progressFrameRect.midX, y: progressFrameRect.midY), radius: progressFrameRect.width / 2, startAngle: -startAngle * CGFloat.pi/180, endAngle: -(endAngle - 179.64) * CGFloat.pi/180, clockwise: true)

        progressColor.setStroke()
        progressFramePath.lineWidth = lineWidth
        progressFramePath.stroke()
    }

}
